### PR TITLE
VC build in librares does not need find_library().

### PR DESCRIPTION
**Pull request by xpol**

### CODE REVIEW

**Comment by ma-bo** [comment]
I agree that you can pass lib names directly to target_link_libraries for MSVC, but I verified that the builds work as expected on MSVC2015 with the find_library() call, so nothing is broken.  If at some point in the future POCO starts supporting MingW builds, the if(WIN32) check would apply there as well, and MingW lib names are in this format: libiphlpapi.a, so the find_library() call is beneficial.

**Comment by xpol** [comment]
I have **cmake 3.6.1** and Visual Studio 2015.

when I run: `cmake -H. -Bbuild -G"Visual Studio 14 2015 Win64" -DLUA_LIB_NAME=lua51 -DLUA_LIB_PATH="..." -DLUA_INCLUDE="..."` 
I got follow error:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBIPHLPAPI
    linked by target "poco" in directory D:/Workspace/lua-poco/src
```

I think i have different version of cmake with you.

**Comment by ma-bo** [comment]
Interesting, the question is, why can it not be found? I upgraded from cmake 3.4.x to cmake 3.6.1 and ran the following two and it built successfully:

cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" -DLUA_INCLUDE=C:\Users\matt\src\lua-5.1.5_Win64_dll14_lib\include -DLUA_LIB_NAME=lua5.1 -DLUA_LIB_PATH=C:\Users\matt\src\lua-5.1.5_Win64_dll14_lib ..

cmake -H. -Bbuild_vs2015 -G "Visual Studio 14 2015 Win64" -DLUA_LIB_NAME=lua5.1 -DLUA_LIB_PATH=C:\Users\matt\src\lua-5.1.5_Win64_dll14_lib -DLUA_INCLUDE=C:\Users\matt\src\lua-5.1.5_Win64_dll14_lib\include ..

Are you running yours from the visual studio tools command prompt with all the paths set properly?

**Comment by xpol** [comment]
I can reproduce it in appveyor:  https://ci.appveyor.com/project/ma-bo/lua-poco/build/4

**Comment by ma-bo** [comment]
The problem is due to the environment not being setup correctly (missing vcvars.bat invocation).  I pushed a test with my known good cmake settings and it built successfully:

https://github.com/ma-bo/lua-poco/blob/c4eeea3c9922ee13e8ebd4d7c764e40b6e4cad68/appveyor.yml
https://ci.appveyor.com/project/ma-bo/lua-poco/build/8

I will merge your other pull request and add the call to vcvars to fix it.

**Pull request closed without merging**
